CREATE TABLE [dbo].[Post]
(
    [Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    [Title] NVARCHAR(200) NOT NULL,
    [Content] NVARCHAR(MAX) NOT NULL,
    [UserId] INT NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO

ALTER TABLE [dbo].[Post]
ADD CONSTRAINT FK_Post_Users FOREIGN KEY (UserId) REFERENCES [dbo].[Users](Id);